on:
  push:
    branches:
      - master


      jobs:
        build: 
          runs_on: ubuntu-latest  

          
          
            

            - users: actions/checkout@v3



            - name: "login to docker" 
              run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}} 


             
              

