on:
  push:
    branches:
      - master


      jobs:
        build: 
          runs_on: ubuntu-latest  

          steps:
            - name: 'before' 
              run: ls

            - users: actions/checkout@v3



            - name: 'before' 
              run: ls


             
              

