on:
  push:
    branches:
      - master


      jobs:
        build: 
          runs_on: ubuntu-latest  

          steps:
            - name: 'printing folder contents' 
              run: ls

             
              

