on:
  push:
    branches:
      - master


      jobs:
        build: 
          runs_on: ubuntu-latest  

          
          
            

            - users: actions/checkout@v3



            - name: "login to docker" 
              run: docker login --username amgedsalah11 --password dckr_pat_t1FW2NYnPn9edaEK0hXkhnKvpbQ 


             
              

